title: Sumant Khalate # your name (or website title) here
logo: "/images/SumantKhalate.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A hobbyist turned engineer who has always loved electronics and has built several projects over the years
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/sumantkhalate//">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
